### ISSUE TITLE
Feature Request: Multiple Targets

### ISSUE THREAD

**Issue by SirNomad49** [exiele/calltarget#1]
is it possible to add multiple targets? like a green and and yellow arrow? that would be nice in RBGs for multiple fights and call stun targets and so on. 

I would suggest /calltarget1, calltarget2 and so on.

**Comment by exiele** [comment]
I need someone to change the marker color, since I don't know how to deal with .tga files

**Comment by exiele** [comment]
managed to edit the marker on gimp and changed color, also already updated the code to put a second marker. just use /calltarget 2 (with a space)
